### ISSUE TITLE
[Feature] Database Driven Interactive Scenes & Objects

### ISSUE THREAD

**Issue by MyNameIsKodos** [CollectiveIndustries/StarfleetDelta#33]
Essentially, this is how the system works/will work;

Let's say the Away Team is on a mission, and come across a strange rock.  Upon [Examine]ing the rock, it's noted that it's quite tall.  If you have a Tricorder equipped, you can [Scan] the rock.  After scanning, the Tricorder announces that the strange rock is in fact an egg to an alien species.

Words in brackets are menu choices, accessed by 'touching' the object in question. A scene would have several interactive objects, depending on what scene it is.

Some objects could possibly even have additional options in the menu that show up after a tricorder scan, such as a revealed hidden button that wasn't known about until after the scan.

This is a WIP concept, and anything and/or everything is subject to change.

**Comment by Morketh** [comment]
I take it this is no longer being worked on or....?
