### ISSUE TITLE
[MySQL] Change the way names are stored

### ISSUE THREAD

**Issue by MyNameIsKodos** [CollectiveIndustries/StarfleetDelta#41]
I was thinking today that name lookups could be done easily with the computer system that's WIP by doing something like

Computer where is Raven
or
Computer where is Lieutenant McQuiston

So instead of having a name field, we should break it apart into fname and lname (first, last)

**Comment by Morketh** [comment]
All of that can be achieved with a simple name ```LIKE %....% ``` query where the ..... in the example is any search string you want to match the % being a wild-card.

**Comment by Morketh** [comment]
This could actually build the frame work for the Relational Database. Simple php script could be written to use the query and search for a string

**Comment by Morketh** [comment]
This is being handled using SID #40
