### ISSUE TITLE
[Acedemy] Missing class DIP-100 Intro to DIPS

### ISSUE THREAD

**Issue by LucineDax** [CollectiveIndustries/StarfleetDelta#47]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by LucineDax** [comment]
First off, this form is too complicated for problem reports.  Secondly, the Academy podium needs the ability to pause a slow down or speed up a class.  The podium desktop needs a control panel to enable this.  Also, the podium is too tall.  Thirdly, I ran a class to demo and when I chose the Intro to DIPS it played the class on Bajorans.  Finally, the classes have random numbers in front of them.  I know they are the old sequence numbers, but they no longer apply and need to be removed

**Comment by Morketh** [comment]
@MyNameIsKodos you may want to revise the Problem report form and adjust the size of the podium.
the seemingly "Random" numbers are what there organized by in the database its the ClassID numbers. [ClassID in StarfleetdeltaInstall.sql](https://github.com/CollectiveIndustries/StarfleetDelta/blob/master/MySQL/StarfleetDelta_Install.sql#L194) this order effects the display in the menu drop down and the class materials.changing this order this will dictate a full reinstall of the class materials and there corresponding Gradebook entries will be invalid as the ClassID is related to the scores. It can be fixed, however its a minor issue and a large task. The reason there in that order is based on the way the files [Academy Materials](https://github.com/CollectiveIndustries/StarfleetDelta/tree/master/doc/sdq_classes) are organized on the disk. Any ordering changes can be made in any order you would like however all the scores and grades for each of those classes are no longer valid. The Intro to DIPS and getting the wrong class is a major issue. I will look into that one as that should be a simple reordering of the ClassID numbers on the proper tables.

**Comment by Morketh** [comment]
in the way of a Pause button if you click and hold for 3 seconds on the podium you will pause the class. an admin menu will be implemented so you can adjust the settings once the class is paused that's on the TODO list as the next milestone on the road-map

**Comment by Morketh** [comment]
Also from the look of it Index 9 relates to [DIP-101](https://github.com/CollectiveIndustries/StarfleetDelta/blob/master/doc/sdq_classes/DIP-101_Rascal_Clean-slate.txt) written by Rascal Clean-Slate which is the Intro to Bajor. according to the class list on file (mentioned above in a link) we do not have a current Intro to DIPS. If you could get the class material in the standardized format and add it as a Pull Request i will be more then happy to apply the class to the database.

**Comment by Morketh** [comment]
[Class upload format](https://github.com/CollectiveIndustries/StarfleetDelta/wiki/Class-upload-format)

**Comment by MyNameIsKodos** [comment]
Closing since there's no Diplomacy DH to write it.  Will reopen in the future if this changes.
