### ISSUE TITLE
[Academy] ASCII/Syntax Errors

### ISSUE THREAD

**Issue by renthegigglefox** [CollectiveIndustries/StarfleetDelta#49]
There appears to be an ASCII/syntax error when referencing the ' (apostrophe) and " (quotation) characters. while testing the system to get a better understanding for how it works, there were errors every time an ' or " was in the class.
Examples:
â€œGood afternoon Admiral Jones and Ms Smithâ€
RPâ€™s

**Comment by MyNameIsKodos** [comment]
Which class was this in?

**Comment by renthegigglefox** [comment]
ACM-102 Civilian Etiquette

**Comment by MyNameIsKodos** [comment]
Fixing it now. Thanks for the report!

**Comment by MyNameIsKodos** [comment]
This should now be fixed!

**Comment by Morketh** [comment]
[ACM-102](https://github.com/CollectiveIndustries/StarfleetDelta/blob/master/doc/sdq_classes/ACM-102_McCole_Avon.txt) This file also needs to reflect the changes in order to keep a clean working copy in the source tree.
